[package]
name = "arcadia-backend"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4"
# there is a possibility to add TLS support (https://github.com/launchbadge/sqlx?tab=readme-ov-file#install)
sqlx = { version = "0.8", features = [
    "runtime-async-std",
    "postgres",
    "chrono",
    "ipnetwork",
] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "1.15.1", features = ["serde", "v4"] }
jsonwebtoken = "9.3.1"
argon2 = "0.5.3"
futures = "0.3"
rand = "0.9.0"
bip_metainfo = "0.12.0"
serde_bytes = "0.11"
actix-multipart = "0.7.2"
actix-files = "0.6.6"
reqwest = { version = "0.12", features = ["json"] }
actix-cors = "0.7.1"
actix-http = "3.10.0"
env_logger = "0.11.8"
thiserror = "2.0.12"
utoipa = { version = "5.3.1", features = ["actix_extras"] }
utoipa-swagger-ui = { version = "9.0.1", features = ["actix-web", "debug-embed"] }
utoipa-actix-web = "0.1.2"
dotenvy = "0.15.7"
percent-encoding = "2.3.1"
serde_bencode = "0.2.4"
musicbrainz_rs = "0.9.1"
actix-web-httpauth = "0.8.2"

[patch.crates-io]
bip_metainfo = { path = "vendored/bip_metainfo" }

[dev-dependencies]
actix-multipart-rfc7578 = "0.11.0"
bytes = "1.10.1"
