use utoipa::OpenApi;

use crate::{
    handlers::{
        artist_handler::GetArtistPublicationsQuery,
        auth_handler::RegisterQuery,
        torrent_handler::{DownloadTorrentQuery, GetTopTorrentsQuery},
    },
    models::{
        artist::{AffiliatedArtist, Artist, ArtistAndTitleGroupsLite, ArtistLite},
        edition_group::EditionGroup,
        forum::{ForumPost, UserCreatedForumPost},
        gift::{Gift, UserCreatedGift},
        invitation::{Invitation, SentInvitation},
        master_group::{MasterGroup, UserCreatedMasterGroup},
        series::{Series, SeriesAndTitleGroupHierarchyLite, UserCreatedSeries},
        title_group::{TitleGroupAndAssociatedData, TitleGroupHierarchy},
        title_group_comment::{TitleGroupComment, UserCreatedTitleGroupComment},
        torrent::{Torrent, TorrentSearch, TorrentSearchResults, TorrentToDelete, UploadedTorrent},
        torrent_report::{TorrentReport, UserCreatedTorrentReport},
        torrent_request::{TorrentRequest, UserCreatedTorrentRequest},
        torrent_request_vote::{TorrentRequestVote, UserCreatedTorrentRequestVote},
        user::{Login, Profile, PublicProfile, PublicUser, Register, User},
    },
};

#[derive(OpenApi)]
#[openapi(
    info(title = "arcadia-backend API",),
    paths(
        crate::handlers::auth_handler::register,
        crate::handlers::auth_handler::login,
        crate::handlers::artist_handler::get_artist_publications,
        crate::handlers::artist_handler::add_artist,
        crate::handlers::artist_handler::add_affiliated_artists,
        crate::handlers::torrent_handler::download_dottorrent_file,
        crate::handlers::torrent_handler::upload_torrent,
        crate::handlers::torrent_handler::find_torrents,
        crate::handlers::torrent_handler::get_top_torrents,
        crate::handlers::torrent_handler::delete_torrent,
        crate::handlers::torrent_report_handler::add_torrent_report,
        crate::handlers::edition_group_handler::add_edition_group,
        crate::handlers::invitation_handler::send_invitation,
        crate::handlers::master_group_handler::add_master_group,
        crate::handlers::series_handler::add_series,
        crate::handlers::series_handler::get_series,
        crate::handlers::subscriptions_handler::add_subscription,
        crate::handlers::subscriptions_handler::remove_subscription,
        crate::handlers::title_group_comment_handler::add_title_group_comment,
        crate::handlers::title_group_handler::add_title_group,
        crate::handlers::title_group_handler::get_title_group,
        crate::handlers::title_group_handler::get_title_group_info_lite,
        crate::handlers::torrent_request_handler::add_torrent_request,
        crate::handlers::torrent_request_vote_handler::add_torrent_request_vote,
        crate::handlers::user_handler::get_user,
        crate::handlers::user_handler::get_me,
        crate::handlers::artist_handler::get_artists_lite,
        crate::handlers::gift_handler::send_gift,
        crate::handlers::forum_handler::add_forum_post,
    ),
    components(schemas(
        Register,
        RegisterQuery,
        Login,
        GetArtistPublicationsQuery,
        DownloadTorrentQuery,
        TorrentSearch,
        Artist,
        AffiliatedArtist,
        User,
        PublicUser,
        EditionGroup,
        Invitation,
        SentInvitation,
        MasterGroup,
        UserCreatedMasterGroup,
        Series,
        UserCreatedSeries,
        UserCreatedTitleGroupComment,
        TitleGroupComment,
        TorrentRequest,
        UserCreatedTorrentRequest,
        TorrentRequestVote,
        UserCreatedTorrentRequestVote,
        UserCreatedTorrentReport,
        TorrentReport,
        ArtistLite,
        SeriesAndTitleGroupHierarchyLite,
        ArtistAndTitleGroupsLite,
        TitleGroupHierarchy,
        TorrentSearchResults,
        TitleGroupAndAssociatedData,
        UploadedTorrent,
        Torrent,
        TorrentToDelete,
        Profile,
        PublicProfile,
        Gift,
        UserCreatedGift,
        GetTopTorrentsQuery,
        ForumPost,
        UserCreatedForumPost
    ),)
)]
pub struct ApiDoc;
