use utoipa::OpenApi;

use crate::{
    handlers::{
        artist_handler::GetArtistPublicationsQuery,
        auth_handler::RegisterQuery,
        home_handler::HomePage,
        scrapers::ExternalDBData,
        torrent_handler::{DownloadTorrentQuery, GetTopTorrentsQuery, UploadInformation},
        torrent_request_handler::SearchTorrentRequestsQuery,
        user_application_handler::{GetUserApplicationsQuery, UpdateUserApplication},
    },
    models::{
        artist::{
            AffiliatedArtist, AffiliatedArtistHierarchy, Artist, ArtistAndTitleGroupsLite,
            ArtistLite,
        },
        conversation::{
            Conversation, ConversationHierarchy, ConversationMessage, ConversationMessageHierarchy,
            ConversationOverview, ConversationsOverview, UserCreatedConversation,
            UserCreatedConversationMessage,
        },
        edition_group::EditionGroup,
        forum::{
            ForumOverview, ForumPost, ForumSubCategoryHierarchy, ForumThreadAndPosts,
            UserCreatedForumPost, UserCreatedForumThread,
        },
        gift::{Gift, UserCreatedGift},
        invitation::{Invitation, SentInvitation},
        master_group::{MasterGroup, UserCreatedMasterGroup},
        series::{Series, SeriesAndTitleGroupHierarchyLite, SeriesLite, UserCreatedSeries},
        title_group::{
            EditedTitleGroup, PublicRating, TitleGroupAndAssociatedData, TitleGroupLite,
        },
        title_group_comment::{TitleGroupComment, UserCreatedTitleGroupComment},
        torrent::{
            EditedTorrent, Extras, Torrent, TorrentSearch, TorrentSearchResults, TorrentToDelete,
            UploadedTorrent,
        },
        torrent_report::{TorrentReport, UserCreatedTorrentReport},
        torrent_request::{
            TorrentRequest, TorrentRequestAndAssociatedData, TorrentRequestFill,
            TorrentRequestHierarchyLite, TorrentRequestWithTitleGroupLite,
            UserCreatedTorrentRequest,
        },
        torrent_request_vote::{
            TorrentRequestVote, TorrentRequestVoteHierarchy, UserCreatedTorrentRequestVote,
        },
        user::{
            EditedUser, Login, LoginResponse, Profile, PublicProfile, PublicUser, RefreshToken,
            Register, User, UserCreatedUserWarning, UserLite, UserWarning,
        },
        user_application::{UserApplication, UserApplicationStatus, UserCreatedUserApplication},
        wiki::{UserCreatedWikiArticle, WikiArticle, WikiArticleHierarchy},
    },
};

#[derive(OpenApi)]
#[openapi(
    info(title = "arcadia-backend API",),
    paths(
        crate::handlers::auth_handler::register,
        crate::handlers::auth_handler::login,
        crate::handlers::user_application_handler::add_user_application,
        crate::handlers::user_application_handler::get_user_applications,
        crate::handlers::user_application_handler::update_user_application_status,
        crate::handlers::auth_handler::refresh_token,
        crate::handlers::home_handler::get_home,
        crate::handlers::artist_handler::get_artist_publications,
        crate::handlers::artist_handler::add_artists,
        crate::handlers::artist_handler::add_affiliated_artists,
        crate::handlers::artist_handler::remove_affiliated_artists,
        crate::handlers::torrent_handler::download_dottorrent_file,
        crate::handlers::torrent_handler::upload_torrent,
        crate::handlers::torrent_handler::edit_torrent,
        crate::handlers::torrent_handler::get_registered_torrents,
        crate::handlers::user_handler::get_registered_users,
        crate::handlers::torrent_handler::get_upload_information,
        crate::handlers::torrent_handler::find_torrents,
        crate::handlers::torrent_handler::get_top_torrents,
        crate::handlers::torrent_handler::delete_torrent,
        crate::handlers::torrent_report_handler::add_torrent_report,
        crate::handlers::edition_group_handler::add_edition_group,
        crate::handlers::invitation_handler::send_invitation,
        crate::handlers::master_group_handler::add_master_group,
        crate::handlers::series_handler::add_series,
        crate::handlers::series_handler::get_series,
        crate::handlers::subscriptions_handler::add_subscription,
        crate::handlers::subscriptions_handler::remove_subscription,
        crate::handlers::title_group_comment_handler::add_title_group_comment,
        crate::handlers::title_group_handler::add_title_group,
        crate::handlers::title_group_handler::edit_title_group,
        crate::handlers::title_group_handler::get_title_group,
        crate::handlers::title_group_handler::get_title_group_info_lite,
        crate::handlers::title_group_handler::search_title_group_info_lite,
        crate::handlers::torrent_request_handler::add_torrent_request,
        crate::handlers::torrent_request_handler::get_torrent_request,
        crate::handlers::torrent_request_handler::fill_torrent_request,
        crate::handlers::torrent_request_vote_handler::add_torrent_request_vote,
        crate::handlers::user_handler::get_user,
        crate::handlers::user_handler::edit_user,
        crate::handlers::user_handler::warn_user,
        crate::handlers::user_handler::get_me,
        crate::handlers::artist_handler::get_artists_lite,
        crate::handlers::gift_handler::send_gift,
        crate::handlers::forum_handler::get_forum,
        crate::handlers::forum_handler::get_forum_sub_category_threads,
        crate::handlers::forum_handler::get_forum_thread,
        crate::handlers::forum_handler::search_forum_thread,
        crate::handlers::forum_handler::add_forum_thread,
        crate::handlers::forum_handler::add_forum_post,
        crate::handlers::wiki_handler::add_wiki_article,
        crate::handlers::wiki_handler::get_wiki_article,
        crate::handlers::conversation_handler::add_conversation,
        crate::handlers::conversation_handler::get_conversation,
        crate::handlers::conversation_handler::get_user_conversations,
        crate::handlers::conversation_handler::add_conversation_message,
        crate::handlers::scrapers::isbn::get_isbn_data,
        crate::handlers::scrapers::musicbrainz::get_musicbrainz_data,
        crate::handlers::scrapers::tmdb::get_tmdb_data,
        crate::handlers::scrapers::comic_vine::get_comic_vine_data,
        crate::handlers::torrent_request_handler::search_torrent_requests,
    ),
    components(schemas(
        Register,
        RegisterQuery,
        Login,
        LoginResponse,
        RefreshToken,
        GetArtistPublicationsQuery,
        DownloadTorrentQuery,
        TorrentSearch,
        Artist,
        AffiliatedArtist,
        AffiliatedArtistHierarchy,
        User,
        PublicUser,
        EditionGroup,
        Invitation,
        SentInvitation,
        MasterGroup,
        UserCreatedMasterGroup,
        Series,
        UserCreatedSeries,
        UserCreatedTitleGroupComment,
        TitleGroupComment,
        TorrentRequest,
        UserCreatedTorrentRequest,
        TorrentRequestVote,
        UserCreatedTorrentRequestVote,
        UserCreatedTorrentReport,
        TorrentReport,
        ArtistLite,
        SeriesAndTitleGroupHierarchyLite,
        ArtistAndTitleGroupsLite,
        TorrentSearchResults,
        TitleGroupAndAssociatedData,
        UploadedTorrent,
        EditedTorrent,
        Torrent,
        TorrentToDelete,
        Profile,
        PublicProfile,
        Gift,
        UserCreatedGift,
        GetTopTorrentsQuery,
        ForumPost,
        UserCreatedForumPost,
        UserWarning,
        UserCreatedUserWarning,
        ForumOverview,
        ForumSubCategoryHierarchy,
        ForumThreadAndPosts,
        UserCreatedForumThread,
        WikiArticle,
        UserCreatedWikiArticle,
        WikiArticleHierarchy,
        ConversationMessage,
        UserCreatedConversation,
        UserCreatedConversationMessage,
        Conversation,
        ConversationHierarchy,
        ConversationMessageHierarchy,
        ConversationOverview,
        ConversationsOverview,
        TorrentRequestHierarchyLite,
        TorrentRequestFill,
        UserApplication,
        UserApplicationStatus,
        UserCreatedUserApplication,
        GetUserApplicationsQuery,
        UpdateUserApplication,
        ExternalDBData,
        HomePage,
        UploadInformation,
        EditedUser,
        PublicRating,
        TorrentRequestWithTitleGroupLite,
        TorrentRequestAndAssociatedData,
        TitleGroupLite,
        EditedTitleGroup,
        Extras,
        SearchTorrentRequestsQuery,
        SeriesLite,
        TorrentRequestVoteHierarchy,
        UserLite,
    ),)
)]
pub struct ApiDoc;
